### ISSUE TITLE
Public function for getting the current action/task

### ISSUE THREAD

**Issue by jonathanj** [ScatterHQ/eliot#257]
We have a use-case where we'd like to store the current Eliot task UUID (or perhaps serialized task identifier) for an audit event, to make any kind of investigation a lot easier. It seems like `eliot._actions.currentAction` is the only way to do this but that's private. Would it make sense to make this public or is there perhaps a better way?

**Comment by itamarst** [comment]
In the past I've used `eliot.Action.serialize_task_id()` for that. It increments the message counter, which is useful in some sense since it tells you exactly where the message came from. OTOH it's not just the UUID, and it's an opaque format with no current guarantees about parseability.

Seems better to just make current action public, and document this use case.
