### ISSUE TITLE
Example request: wrapping other loggers

### ISSUE THREAD

**Issue by BoltzmannBrain** [ScatterHQ/eliot#299]
In the eliot [podcast.\_\_init\_\_ episode](https://www.podcastinit.com/eliot-logging-with-itamar-turner-trauring-episode-133/) it's mentioned that eliot can be implemented as a wrapper around a user's existing logger (e.g. the Python system logging). It would be great to see an example of this.

For some context, my use case is unifying Python's system logging with ROS logging (i.e. `rospy.log()`) s.t. the program has one consistent log-level and calls to either (Python or ROS) are captured. Is there a way to unify these two logging systems within an eliot module? Any help is greatly appreciated!

**Comment by itamarst** [comment]
Do you specifically want Eliot's features, or just looking to unify stdlib and ROS logging? If your only use case is unifying stdlib logging and ROS logging, Eliot will just complicate things.

**Comment by BoltzmannBrain** [comment]
Eliot's features would be great; the ROS logging system is in need of better functionality.

**Comment by itamarst** [comment]
OK, so the thing to do is have Eliot be the main logging system, the thing that writes the output. Then, route logging messages from other systems to it.

For example, for stdlib logging you'd do the following (untested):

```
import logging
from eliot import Message

class EliotLogHandler(logging.Handler):
    def emit(self, record):
        Message.log(message_type="stdlib", level=record.level, message=record.getMessage())

logging.getLogger().addHandler(EliotLogHandler())
```

Now every message from stdlib gets turned into an eliot Message... and because of automatic context it'll usually be inside the relevant Eliot action. Need to write a bit more code to handle exceptions nicely, but that's the essence of it.

(I will at some point try to make this into an Eliot feature, but feel free to submit a PR if you feel like it.)

Does this answer your question?

**Comment by BoltzmannBrain** [comment]
Yes this is helpful, thanks @itamarst! And yes the ability to easily wrap existing loggers would be a really useful feature.
If my implementation is any good I'll be sure to open a PR 👍
